<a href="https://colab.research.google.com/github/Repocr/Code-Decode-tool/blob/master/Estudiantes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Pandas**

## **Importando la base de datos estudiantes**

In [28]:
import pandas as pd

url= "https://gist.githubusercontent.com/ahcamachod/807a2c1cf6c19108b2b701ea1791ab45/raw/fb84f8b2d8917a89de26679eccdbc8f9c1d2e933/alumnos.csv"
pd.read_csv(url)

      Nombre  Edad  Nota   Aprobado
0    Alberto    20   7.5       True
1        Ana    18   NaN      False
2     Camila    27   2.5      False
3      David    18   5.0      False
4      Brian    21  10.0       True
5      Bruna    23   NaN      False
6    Daniela    21   7.0       True
7     Carlos    19   6.0      False
8     Alicia    35   5.6      False
9     Victor    28   NaN      False
10    Danilo    21   NaN      False
11   Ignacio    24   4.5      False
12  Stephany    26  10.0       True
13    Miriam    25   9.0       True
14     Pablo    37   NaN      False
15    Milena    29   7.0       True
16     Lucas    33   NaN      False
17     Nadia    34   8.0  Verdadero

In [33]:
pd.read_csv(url, sep=',')

      Nombre  Edad  Nota   Aprobado
0    Alberto    20   7.5       True
1        Ana    18   NaN      False
2     Camila    27   2.5      False
3      David    18   5.0      False
4      Brian    21  10.0       True
5      Bruna    23   NaN      False
6    Daniela    21   7.0       True
7     Carlos    19   6.0      False
8     Alicia    35   5.6      False
9     Victor    28   NaN      False
10    Danilo    21   NaN      False
11   Ignacio    24   4.5      False
12  Stephany    26  10.0       True
13    Miriam    25   9.0       True
14     Pablo    37   NaN      False
15    Milena    29   7.0       True
16     Lucas    33   NaN      False
17     Nadia    34   8.0  Verdadero

In [31]:
datos = pd.read_csv(url, sep=',')

In [32]:
datos

      Nombre  Edad  Nota   Aprobado
0    Alberto    20   7.5       True
1        Ana    18   NaN      False
2     Camila    27   2.5      False
3      David    18   5.0      False
4      Brian    21  10.0       True
5      Bruna    23   NaN      False
6    Daniela    21   7.0       True
7     Carlos    19   6.0      False
8     Alicia    35   5.6      False
9     Victor    28   NaN      False
10    Danilo    21   NaN      False
11   Ignacio    24   4.5      False
12  Stephany    26  10.0       True
13    Miriam    25   9.0       True
14     Pablo    37   NaN      False
15    Milena    29   7.0       True
16     Lucas    33   NaN      False
17     Nadia    34   8.0  Verdadero

In [35]:
datos.head(8)

    Nombre  Edad  Nota Aprobado
0  Alberto    20   7.5     True
1      Ana    18   NaN    False
2   Camila    27   2.5    False
3    David    18   5.0    False
4    Brian    21  10.0     True
5    Bruna    23   NaN    False
6  Daniela    21   7.0     True
7   Carlos    19   6.0    False

In [36]:
datos.tail(6)

      Nombre  Edad  Nota   Aprobado
12  Stephany    26  10.0       True
13    Miriam    25   9.0       True
14     Pablo    37   NaN      False
15    Milena    29   7.0       True
16     Lucas    33   NaN      False
17     Nadia    34   8.0  Verdadero

In [37]:
type(datos)

pandas.core.frame.DataFrame

## **Exploracion inicial delos datos**

cantidad de flias y 9 columnas

In [38]:
datos.shape

(18, 4)

In [39]:
datos.columns

Index(['Nombre', 'Edad', 'Nota', 'Aprobado'], dtype='object')

In [40]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Nombre    18 non-null     object
 1   Edad      18 non-null     int64
 2   Nota      12 non-null     float64
 3   Aprobado  18 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 704.0+ bytes

In [42]:
datos['Nombre']

0      Alberto
1          Ana
2       Camila
3        David
4        Brian
5        Bruna
6      Daniela
7       Carlos
8       Alicia
9       Victor
10      Danilo
11     Ignacio
12    Stephany
13      Miriam
14       Pablo
15      Milena
16       Lucas
17       Nadia
Name: Nombre, dtype: object

In [43]:
datos[['Aprobado','Edad']]

     Aprobado  Edad
0        True    20
1       False    18
2       False    27
3       False    18
4        True    21
5       False    23
6        True    21
7       False    19
8       False    35
9       False    28
10      False    21
11      False    24
12       True    26
13       True    25
14      False    37
15       True    29
16      False    33
17  Verdadero    34